num_righe(10).
num_colonne(10).

iniziale(pos(1,1)).
finale(pos(7,10)).
finale(pos(10,1)).

occupata(pos(1,9)).
occupata(pos(2,2)).
occupata(pos(2,4)).
occupata(pos(2,5)).
occupata(pos(2,6)).
occupata(pos(2,7)).
occupata(pos(2,9)).
occupata(pos(3,6)).
occupata(pos(4,1)).
occupata(pos(4,2)).
occupata(pos(4,3)).
occupata(pos(4,4)).
occupata(pos(4,6)).
occupata(pos(4,7)).
occupata(pos(4,9)).
occupata(pos(5,2)).
occupata(pos(5,4)).
occupata(pos(5,6)).
occupata(pos(5,7)).
occupata(pos(5,9)).
occupata(pos(6,9)).
occupata(pos(7,1)).
occupata(pos(7,2)).
occupata(pos(7,4)).
occupata(pos(7,5)).
occupata(pos(7,6)).
occupata(pos(7,7)).
occupata(pos(7,8)).
occupata(pos(7,9)).
occupata(pos(8,9)).
occupata(pos(9,1)).
occupata(pos(9,2)).
occupata(pos(9,3)).
occupata(pos(9,4)).
occupata(pos(9,5)).
occupata(pos(9,6)).
occupata(pos(9,7)).
occupata(pos(9,9)).